[project]
name = "mcp-server"
version = "0.1.0"
description = "biotools mcp server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.10.1",
    "fastmcp>=2.10.2",
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
]
